### ISSUE TITLE
ExchangeRate how to?

### ISSUE THREAD

**Issue by Matto791** [AutomateValue/NodaMoney#90]
You have a lot of examples on the frontpage, but the one I actually need isn't there, exhange rate. Can this actually convert an existing sum from one currency to another? So far I haven't figured out how to do it i.e. EUR to GBP

**Comment by remyvd** [comment]
`ExchangeRate` is a domain object that can be used to do conversion, but there are no providers added to NodaMoney to get the real exchange rates from a certain source.

```
// EUR/USD 1.2591
var eurUsdFx = new ExchangeRate(Currency.FromCode("EUR"), Currency.FromCode("USD"), 1.2591);

// Convert €100,99 to $127.156509 (= €100.99 * 1.2591)
Money dollars = _exchangeRate.Convert(Money.Euro(100.99M));
```

See also https://github.com/AutomateValue/NodaMoney/blob/master/tests/NodaMoney.Tests/ExchangeRateSpec.cs
